version: '3'
services:
    api:
       build: .
       depends_on:
            - postgres
       ports:
            - 8000:8000

       env_file:
            - ./.env

    postgres:
      image: postgres
      user: postgres
      environment:
          - POSTGRES_PASSWORD=password123
          - POSTGRES_DB=fastapi
      volumes:
          - postgres-db:/var/lib/postgresql/data
      healthcheck:
          test: [ "CMD", "pg_isready" ]
          interval: 10s
          timeout: 5s
          retries: 5     

volumes:
     postgres-db:          

      


    