name: Build & deploy

on: [push]
jobs:
  build_and_test:
    environment: testing
    env:
      DB_URL: ${{secrets.DB_URL}}
      SECRET_key: ${{secrets.SECRET_key}}
      Token_Expire_Time_Min: ${{secrets.Token_Expire_Time_Min}}
      Algorithm: ${{secrets.Algorithm}}

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: echo "welcome to fastAPI by Dev Lokesh"

      - uses: ikalnytskyi/action-setup-postgres@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - run: python -m pip install --upgrade pip
   
      - run: pip install -r requirements.txt

      - run: pytest -vv tests/
  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    environment: deployment
    steps:
      - uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.Railway_API_KEY}}
          service: "FastAPI" 