name: Build 

on: [push]
jobs:
  build and test (CI):
    environment : testing
    env:
      DB_URL: ${{secrets.DB_URL}}
      SECRET_key: ${{secrets.SECRET_key}}
      Token_Expire_Time_Min: ${{secrets.Token_Expire_Time_Min}}
      Algorithm: ${{secrets.Algorithm}}

    services:
      postgres :
        image: postgres  
        env:
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PSWD}}
          POSTGRES_DB: ${{secrets.DB_NAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5    
    runs-on: ubuntu-latest
    steps: 
      - name : pull git repository
      - uses: actions/checkout@v4
      - name : welcome msg
      - run : echo "welcome to fastAPI by Dev Lokesh"
      - name : setup python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name : update pip
      - run : python -m pip install --upgrade pip
      - name : install dependencies
      - run : pip install -r requirements.txt
      - name : running tests 
      - run : |
          pip install pytest
          pytest -v