name: Build 

on: [push]
jobs:
  build_and_test:
    environment: testing
    env:
      DB_URL: ${{secrets.DB_URL}}
      SECRET_key: ${{secrets.SECRET_key}}
      Token_Expire_Time_Min: ${{secrets.Token_Expire_Time_Min}}
      Algorithm: ${{secrets.Algorithm}}

    services:
      postgres :
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PSWD}}
          POSTGRES_DB: ${{secrets.DB_NAME}}
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5    
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: echo "welcome to fastAPI by Dev Lokesh"
     
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - run: python -m pip install --upgrade pip
   
      - run: pip install -r requirements.txt

      - run: pytest 
